# Safe keys to merge if your build is acting up
baseurl: ""    # for user sites like username.github.io

theme: null

plugins:
  - jekyll-feed

exclude:
  - vendor
  - vendor/**/*
  - Gemfile
  - Gemfile.lock
  - node_modules
