title: Binary Executioner
description: >- 
  Personal blog for red teaming, blue teaming, threat hunting, and malware development.
repository: BinaryExecutioner/BinaryExecutioner.github.io
# Safe keys to merge if your build is acting up
baseurl: ""    # for user sites like username.github.io
repository: BinaryExecutioner/BinaryExecutioner.github.io
theme: null
defaults:
  - scope: { path: "", type: "posts" }
    values: { layout: post }
plugins:
  - jekyll-feed

exclude:
  - vendor
  - vendor/**/*
  - Gemfile
  - Gemfile.lock
  - node_modules
